# Generated by Django 4.1.6 on 2023-08-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('mobie', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='author',
        ),
        migrations.DeleteModel(
            name='TodoS',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
